---
title: "finreportr test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries

library(finreportr)
library(tidyverse)
```

```{r}
# get the balance sheet for $AAPL from 2017
bl <- GetBalanceSheet("AAPL", 2020)
bl_df <- tibble(bl)
bl_df$Amount <- bl_df$Amount %>% as.numeric()


# get cashflow statement from $AAPL, 2017
cf <- GetCashFlow("AAPL", 2017)
cf_df <- tibble(cf)
cf_df$Amount <- cf_df$Amount %>% as.numeric()


# get income statement from $AAPL 2017
is <- GetIncome("AAPL", 2017)
is_df <- tibble(is)
is_df$Amount <- is_df$Amount %>% as.numeric()
```

```{r}
netrevenue <- filter(is_df, Metric == "Revenue, Net")
assets <- filter(bl_df, Metric == "Assets")

revenue_to_assets =(tail(netrevenue$Amount, 1))/(tail(assets$Amount, 1))
revenue_to_assets
```

```{r}
cash <- cf_df %>%
  filter(Metric == "Cash and Cash Equivalents, at Carrying Value")

gross_profit <- is_df %>%
  filter(Metric == "Gross Profit")

cash_to_gross_proft = tail(cash$Amount, 1)/tail(gross_profit$Amount, 1)
cash_to_gross_proft
```

