---
title: "R4DS - Ch 5"
author: "Eugene Zhou"
date: "4/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(nycflights13)

flights

summarise(flights, delay = mean(dep_delay, na.rm = TRUE))
by_day <- group_by(flights, year, month, day)
summarise(by_day, delay = mean(dep_delay, na.rm = TRUE))

```

```{r}
### General Data Processing
#group flights by destination
by_dest <- group_by(flights, dest)

#summarise distance, avg delay, and number of flights
delay <- summarise(by_dest, 
                   count = n(),
                   dist = mean(distance, na.rm = TRUE), 
                   delay = mean(arr_delay, na.rm = TRUE)
                   )

#filter out Honolulu airport
delay <- filter(delay, count > 20, dest != "HNL")

#plot filtered data 
ggplot(data = delay, mapping = aes(x = dist, y = delay)) +
  geom_point(aes(size = count), alpha = 1/3) + 
  geom_smooth(se = FALSE)
```

```{r}
### Data Processing with Pipe

delays <- flights %>%
  group_by(dest) %>%
  summarise(
    count = n(), 
    dist = mean(distance, na.rm = TRUE), 
    delay = mean(arr_delay, na.rm = TRUE)
  ) %>%
  filter(count > 20, dest !="HNL")
```


```{r}
flights %>%
  group_by(year, month, day) %>%
  summarise(mean = mean(dep_delay))

flights %>% 
  group_by(year, month, day) %>%
  summarise(mean = mean(dep_delay, na.rm = TRUE))

not_cancelled <- flights %>%
  filter(!is.na(dep_delay), !is.na(arr_delay))

not_cancelled %>%
  group_by(year, month, day) %>%
  summarise(mean = mean(dep_delay))
```

```{r}
### plotting counts of aggregated data

delays <- not_cancelled %>%
  group_by(tailnum) %>%
  summarise(
    delay = mean(arr_delay)
  )

ggplot(data = delays, mapping = aes(x=delay)) + 
  geom_freqpoly(binwidth = 10)

```

```{r}
### scatter plot of aggregated data

delays <- not_cancelled %>%
  group_by(tailnum) %>%
  summarise(
    delay = mean(arr_delay, na.rm = TRUE), 
    n = n()
  )

ggplot(data = delays, mapping = aes(x = n, y = delay)) + 
  geom_point(alpha = 1/10)
```

```{r}
delays %>%
  filter(n > 25) %>%
  ggplot(mapping = aes(x = n, y = delay)) + 
  geom_point(alpha = 1/10)
```

```{r}
### plot batting avg

# convert to a tibble so it print nicely
batting <- as_tibble(Lahman::Batting)

batters <- batting %>%
  group_by(playerID) %>%
  summarise(
    ba = sum(H, na.rm = TRUE) / sum(AB, na.rm = TRUE), 
    ab = sum(AB, na.rm = TRUE)
  )

batters %>%
  filter(ab > 100) %>%
  ggplot(mapping = aes(x = ab, y = ba)) + 
  geom_point() + 
  geom_smooth(se = FALSE)

```

```{r}
batters %>% 
  arrange(desc(ba))
```

```{r}
not_cancelled %>%
  group_by(year, month, day) %>%
  summarise(
    avg_delay1 = mean(arr_delay), 
    avg_delay2 = mean(arr_delay[arr_delay > 0])
  )

not_cancelled %>%
  group_by(dest) %>%
  summarise(distance_sd = sd(distance)) %>%
  arrange(desc(distance_sd))

not_cancelled %>%
  group_by(year, month, day) %>%
  summarise(
    first = min(dep_time), 
    last = max(dep_time)
  )
```

```{r}

not_cancelled %>%
  group_by(year, month, day) %>%
  summarise(
    first_dep = first(dep_time), 
    last_dep = last(dep_time)
  )
  
```

```{r}

not_cancelled %>%
  group_by(year, month, day) %>%
  mutate(r = min_rank(desc(dep_time))) %>%
  filter(r %in% range(r))
  
```

```{r}
# Which destinations have the most carriers?

not_cancelled %>%
  group_by(dest) %>%
  summarise(carriers = n_distinct(carrier)) %>%
  arrange(desc(carriers))

```

```{r}

not_cancelled %>%
  count(dest)

```

```{r}

not_cancelled %>%
  count(tailnum, wt = distance)

```

```{r}

not_cancelled %>% 
  group_by(year, month, day) %>%
  summarise(n_early = sum())

```

```{r}
### grouping by multiple variables

daily <- group_by(flights, year, month, day)

#sum of flights per day
(per_day <- summarise(daily, flights = n()))

#sum of flights per month
(per_month <- summarise(per_day, flights = sum(flights)))

#sum of flights per year
(per_year <- summarise(per_month, flights = sum(flights)))

```

```{r}
### ungroup data

daily %>%
  ungroup() %>% 
  summarise(flights = n())
```

```{r}
view(flights)
head(flights)
```


```{r}
### Exercises

delays <- flights %>%
  group_by(dest) %>%
  summarise(
    count = n(), 
    dist = mean(distance, na.rm = TRUE), 
    delay = mean(arr_delay, na.rm = TRUE)
  ) %>%
  filter(count > 20, dest !="HNL")

sum(flights$dest=="ABQ")

# flight 15 min early 50% of the time and 15 min late 50% of the time

not_cancelled <- flights %>%
  filter(!is.na(dep_delay), !is.na(arr_delay))

group_by(not_cancelled, carrier) %>%
  mutate(late = dep_delay==15, 
         early = dep_delay == -15, 
         late50) %>%



Early15min_Late15min <- group_by(not_cancelled, tailnum) %>%
  filter(dep_delay == 15 | dep_delay == -15) %>%
  group_by(dep_delay)

summarise(Early15min_Late15min, mean = mean(arr_delay))

#flight always 10 min late

alwaysLate <- group_by(not_cancelled, tailnum) %>%
  filter(dep_delay == -10) %>%
  select(carrier, tailnum, year, month, day, dep_delay, arr_delay)

head(alwaysLate)

#flight is 30 min early 50% of the time and 30 min late 50% of the time

early30late30 <- group_by(flights, tailnum) %>%
  filter(dep_delay == 30 | dep_delay == -30) %>%
  select(carrier, tailnum, year, month, day, dep_delay, arr_delay)

head(early30late30)


# 99% of flights on time 1% 2 hrs late

sometimesLate <- filter(flights, dep_delay == 0 | dep_delay == 120) %>%
  select(carrier, tailnum, year, month, day, dep_delay, arr_delay)

head(sometimesLate)

```




