---
title: "Rmarkdown_TRGN599_Week_8_Lecture_10"
author: "Enrique I. Velazquez Villarreal, MD, PhD, MPH, MS"
date: "3/18/2019"
output: html_document
---



## R Markdown
## Analysis of Categorical Variables

# chisq.test() function is used to test a hypothesis regarding the probabilities (population proportions) of different categories for a categorical variable, it performs Pearson’s χ2 test.
```{R}
chisq.test(x = c(24, 16), p = c(0.7, 0.3))
```

# We can also use the chisq.test() function for categorical variables with multiple categories.
```{R}
chisq.test(x = c(13, 11, 16), p = c(0.5, 0.2, 0.3))
```

# The following code creates the contingency table for smoke by low from the birthwt data set and then performs the χ 2 test to examine their relationship:

```{R}
# install.packages("MASS")
library(MASS)
birthwt.tab <- table(birthwt$smoke, birthwt$low)
birthwt.tab
```


# Running chisq.test
```{R}
chisq.test(birthwt.tab, correct = FALSE)
```

# Entering a Contingency table directly in R
```{R}
contTable <- matrix(c(189, 10845, 104, 10933), nrow=2,ncol=2,byrow=TRUE)
rownames(contTable) <- c("Placebo", "Aspirin") 
colnames(contTable) <- c("No heart attack", "Heart attack")
contTable
```

# Using chisq.test() function to examine the relationship between two variables
```{R}
output <- chisq.test(contTable, correct = FALSE)
output
```

# Obtaining the observed frequencies with the $ operator
```{R}
output$observed
```

# Obtaining the expected frequencies with the $ operator
```{R}
output$expected
```

# EXERCISE 1

# Examine the relationship between these two categorical variables (ht and low)
```{R}
# install.packages("MASS")
library(MASS)
#birthHT.tab <- table(as.factor(birthwt$ht), as.factor(birthwt$low))
birthHT.tab <- table(birthwt$ht,birthwt$low)
birthHT.tab
```

# Examine the relationship between these two categorical variables (ht and low)
```{R}
chisq.test(birthHT.tab, correct = FALSE)
```

# EXERCISE 2

# Creating a 4×2 tab.
```{R}
contTable <- matrix(c(24, 1355, 35, 603, 21, 192, 30, 224), nrow=4,ncol=2, byrow=TRUE)
rownames(contTable) <- c("Never", "Occasionally", "Nearly every night", "Every night") 
colnames(contTable) <- c("Heart Disease", "No Heart Disease")
contTable
```

# Running Pearson’s χ2 test in the 4×2 tab.
```{R}
chisq.test(contTable)
```

# Using Fisher exact test
# weight.status and type

```{R}
contTable <- matrix(c(2, 0, 21, 2, 35, 8, 74, 58), nrow=4,ncol=2, byrow=TRUE)
rownames(contTable) <- c("Underweight", "Normal", "Overweight", "Obese") 
colnames(contTable) <- c("No", "Yes")
contTable
```

# Running Pearson’s χ2 test.
```{R}
chisq.test(contTable)
```

# Running Fisher's exact test.
```{R}
fisher.test(contTable)
```
