---
title: "Rmarkdown_TRGN599_Week_8_Lecture_1"
author: "Enrique I. Velazquez Villarreal, MD, PhD, MPH, MS"
date: "2/25/2019"
output: html_document
---


# ANNOVA analysis
# Use Cushing data from MASS package

#Checking your R working directory
```{R}

# Check your current working directory
getwd()

# Set your working directory
setwd("/Users/enriquevelazquez/Documents/R_working_directory")

```

# Load Data in R
```{R}

library(MASS)
library(magrittr)
library(dplyr)
head(Cushings)
Cushings

```

# Summarizing data
```{R}
summary(Cushings)
```
# Summarizing data
```{R}
# Cuchings_db <- Cushings %>%
# select(Tetrahydrocortisone, Pregnanetriol, Type) %>%
# group_by(Type) %>%
# summarise(Tetrahydrocortisone = mean(Tetrahydrocortisone), Pregnanetriol = mean(Pregnanetriol))
# 
# Cuchings_db
```
# Plotting data
```{R}
average_Tetra <- mean(Cushings$Tetrahydrocortisone)
plot(Cushings$Type, Cushings$Tetrahydrocortisone, main="TRGN599: Tetrahydrocortisone by Syndrome Type", xlab="Type", ylab="Tetrahydrocortisone")

```

# Plotting data
```{R}

dotchart(as.numeric(Cushings$Tetrahydrocortisone), Cushings$Type, main="TRGN599: Tetrahydrocortisone by Syndrome Type", xlab="Tetrahydrocortisone")

```


# We can use the function aov() to perform ANOVA directly. 
# Here the response variable is Tetrahydrocortisone, and the factor is Type:
```{R}

library(MASS)
data(Cushings)
TRGN599_anova_TT <- aov(Tetrahydrocortisone ~ Type, data = Cushings)

```

# Summarizing
```{R}

summary(TRGN599_anova_TT)

```

```{R}
#install.packages("RcmdrMisc")
library(RcmdrMisc)
numSummary(Cushings$Tetrahydrocortisone, groups=Cushings$Type, statistics = c("mean", "sd"))

```

# For two-way ANOVA, we use also use aov().
# but the right side of the formula includes both factors. 

```{R}
library(MASS)
data(genotype)
TRGN599_anova_ML <- aov(Wt ~ Mother + Litter, data = genotype)
```

# Summarizing
```{R}

summary(TRGN599_anova_ML)

```

# To include the interaction of the two factors in the ANOVA model, we use “*” instead of “+”.
```{R}

library(MASS)
data(genotype)
TRGN599_anova_MLi <- aov(Wt ~ Mother * Litter, data = genotype)

```


# Summarizing
```{R}

summary(TRGN599_anova_MLi)

```

# Ploting F
```{R}
F <- Cushings$Tetrahydrocortisone
dF <- df(x=F, df1=3, df2=23)
plot(F, dF)
```

# Ploting F
```{R}
plot(F, dF, type="l", lwd=3, col="blue")
```

# Ploting Density function
```{R}
d <- density(Cushings$Tetrahydrocortisone) # returns the density data 
plot(d) # plots the results
```

# Printing Genotype database
```{R}
genotype
```

# After we obtain f , the observed value of the F -statistic, we can use the F -distribution to obtain the corresponding p-value by calculating the upper tail probability of f.
# The upper tail probability of 3.2 is obtained as follows:
# Note that we need to set the lower.tail to “FALSE” to obtain the upper tail probability.
```{R}
pf(3.2, df1 = 3, df2 = 23, lower.tail = FALSE)
```

