---
title: "Rmarkdown_TRGN599_Assignment_5"
author: "Enrique I. Velazquez Villarreal, MD, PhD, MPH, MS"
date: "2/21/2019"
output: html_document
---


# Assignment 5
# Correlations analysis

```{R}

# Check your current working directory
getwd()

# Set your working directory
setwd("/Users/enriquevelazquez/Documents/R_working_directory")

```

## Uploading datasets
```{R}
library(dplyr)

samples <- read.csv('TRGN599_sample_info_A5.csv', header = TRUE, sep = ",", quote = "'", dec = ".", fill = TRUE, row.names = 1)
 
genes <- read.csv('TRGN599_expression_results_A5.csv',header = TRUE, sep = ",", quote = "'", dec = ".", fill = TRUE, row.names = 1)

```

# 1) Plot the genes KITA_23 vs KITA_24 
## Ploting - looking at a little better
```{R}

plot(genes$KITA_23,genes$KITA_24)

``` 

# 2) Plot the genes KITA_11 vs KITA_12 
## Ploting - looking at a little better
```{R}

plot(genes$KITA_11,genes$KITA_12)

``` 

# 3) Plot the genes KITA_10 vs KITA_11 
## Ploting - looking at a little better
```{R}

plot(genes$KITA_10,genes$KITA_11)

```


# 4) Plot the genes KITA_15 vs KITA_16 
## Ploting - looking at a little better
```{R}

plot(genes$KITA_15,genes$KITA_16)

```

# 5) Plot the genes KITB_15 vs KITB_16 
## Ploting - looking at a little better
```{R}

plot(genes$KITB_15,genes$KITB_16)

```


# 6) Make a distribution of KITB_11 using the "density()"" function

```{R}
 
d <- density(genes$KITB_11) # returns the density data
plot(d) # plots the results
 
```

# 7) What is the N of the KITB_11
# Answer: 63677

# 8) What is the Bandwith of the KITB_11
# Answer: 0.197



# 9) Make a density plot with the log2 transformation of the values in KITA_24
## Graphing on a log plot
```{R}

plot(density(log2(genes$KITA_24[(genes$KITA_24>0)])))

```

# 10) What is the N of the KITA_24
# Answer: 55264

# 11) What is the Bandwith of the KITA_24
# Answer: 0.3483


#12) Plot the log2 values of KITA_23 VS KITA_24
```{R}

plot(log2(genes$KITA_01[(genes$KITA_23>0 |genes$KITA_24>0 )]),log2(genes$KITA_24[(genes$KITA_23>0 |genes$KITA_24>0 )]))

```

# 13) Correlate all the genes in the expression data file and show the first five rows and the last five columns.
## Correlation function
```{R}
dim(genes)
corr<-cor(genes)
corr[1:5,44:48]

```

# 14) Correlate all the genes in the expression data file and show the first five rows and the first five columns.
```{R}
dim(genes)
corr<-cor(genes)
corr[1:5,1:5]

```



# 15) Using the melt() and ggplotly() functions, create an interactive heatmap of the expression data. 
## Reshaping this as a list of pairs
```{R}

#install.packages("reshape2")
#install.packages("ggplot2")

library(ggplot2)
library(reshape2)
library(plotly)

corr<-cor(genes)
melted_corr <- melt(corr)
p<-ggplot(melted_corr , aes(x = Var1, y = Var2)) + geom_raster(aes(fill = value)) + scale_fill_gradient2(low="navy", mid="white", high="red", midpoint=0.5) + theme( plot.title = element_blank(),axis.text.x = element_blank(), axis.text.y = element_blank(), axis.title.y = element_blank(), axis.title.x = element_blank())
ggplotly(p)

```





